import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/ThemeProvider";
import { Header } from "@/components/ui/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yuvidew108",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-y-auto dark:bg-[#1f1f1f]`}>
        <ThemeProvider
          attribute = "class"
          defaultTheme = "system"
          enableSystem
          disableTransitionOnChange
          storageKey = "profile-theme-2"
        >
          <Header/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
